import type { Metadata } from "next";
import { nasa, roboto } from "./components/fonts";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${nasa.variable} ${roboto.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
function localFont(arg0: { src: string }) {
  throw new Error("Function not implemented.");
}
